### ISSUE TITLE
release 0.2.1 to npm

### ISSUE THREAD

**Issue by gurumusch** [eacg-gmbh/ecs-node-client#2]
Hi, in npm the latest version is still 0.2.0. Can v0.2.1 be released to npm? We could then use it in automated builds on Windows.

**Comment by gurumusch** [comment]
Das habe ich gestern auch getan. Aber ich habe einfach nicht die Rechte, um das Projekt auf npmjs.com zu publishen.

**Comment by jthDEV** [comment]
Ok, ich hatte das falsch verstanden. Oleksandr kümmert sich darum.

Von: Andreas <notifications@github.com>
Antworten an: eacg-gmbh/ecs-node-client <reply@reply.github.com>
Datum: Mittwoch, 19. September 2018 um 10:28
An: eacg-gmbh/ecs-node-client <ecs-node-client@noreply.github.com>
Cc: Jan Thielscher <jan.thielscher@eacg.de>, Comment <comment@noreply.github.com>
Betreff: Re: [eacg-gmbh/ecs-node-client] release 0.2.1 to npm (#2)


Das habe ich gestern auch getan. Aber ich habe einfach nicht die Rechte, um das Projekt auf npmjs.com zu publishen.

**Comment by olexandrbig** [comment]
https://www.npmjs.com/package/ecs-node-client
